# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install with Maven
      run: mvn install -DskipTests -Dgpg.skip --quiet
    - name: Compile with Maven
      run: mvn clean compile assembly:single
    - name: Spotless check
      run: mvn spotless:check
    - name: FrontendTests
      run: mvn -Dtest=FrontendTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: RuntimeTests
      run: mvn -Dtest=RuntimeTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: RuntimeTestsNoParallelism
      run: mvn -Dtest=RuntimeTestsNoParallelism test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: RuntimeTestsNoInlining
      run: mvn -Dtest=RuntimeTestsNoInlining test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: StaticTypeTests
      run: mvn -Dtest=StaticTypeTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: JavaAPITest
      run: mvn -Dtest=JavaAPITest test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: Copying artefacts
      run: mkdir staging && cp target/*.jar staging
    - name: Package
      uses: actions/upload-artifact@v3
      with:
        name: Package
        path: staging

  tests2:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install with Maven
      run: mvn install -DskipTests -Dgpg.skip --quiet
    - name: Compile with Maven
      run: mvn clean compile assembly:single
    - name: SparkRuntimeTests
      run: mvn -Dtest=SparkRuntimeTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: SparkRuntimeTestsNativeDeactivated
      run: mvn -Dtest=SparkRuntimeTestsNativeDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: SparkRuntimeTestsDataFramesDeactivated
      run: mvn -Dtest=SparkRuntimeTestsDataFramesDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: SparkRuntimeTestsParallelismDeactivated
      run: mvn -Dtest=SparkRuntimeTestsParallelismDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"

  tests3:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Java 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: adopt
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
    - name: Install with Maven
      run: mvn install -DskipTests -Dgpg.skip --quiet
    - name: Compile with Maven
      run: mvn clean compile assembly:single
    - name: Bugs
      run: mvn -Dtest=Bugs test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: NativeFLWORRuntimeTests
      run: mvn -Dtest=NativeFLWORRuntimeTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: NativeFLWORRuntimeTestsNativeDeactivated
      run: mvn -Dtest=NativeFLWORRuntimeTestsNativeDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: NativeFLWORRuntimeTestsDataFramesDeactivated
      run: mvn -Dtest=NativeFLWORRuntimeTestsDataFramesDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: NativeFLWORRuntimeTestsParallelismDeactivated
      run: mvn -Dtest=NativeFLWORRuntimeTestsParallelismDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: MLTests
      run: mvn -Dtest=MLTests test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"
    - name: MLTestsNativeDeactivated
      run: mvn -Dtest=MLTestsNativeDeactivated test -DargLine="--add-opens=java.base/java.nio=ALL-UNNAMED --add-opens=java.base/java.lang.invoke=ALL-UNNAMED --add-opens=java.base/java.util=ALL-UNNAMED"

